### ISSUE TITLE
[Bug]: Opening action info freezes app

### ISSUE THREAD

**Issue by gabihorvath** [foundryvtt/foundryvtt-premium-content#822]
### What happened?

Environment: Selfhosted headless linux version running through pm2. German language.
I don't know if this only affects my german version, or other languages. If I check the sheet of the "Koboldfallenstellerin" in room 11 and click on the action "Schnelles Fallenstellen" to see the details, nothing happens. The app freezes (JS doesn't work anymore). The click doesn't trigger any console logs or network traffic. Only hard reloading brings back the app. There are no related (error-)logs server wise.

### What package are you reporting this for?

Pathfinder: Beginner Box

### Version

4.0.2

**Comment by silvative** [comment]
Hi, I'm sorry to hear about the problem you're having! I hope we can get to the bottom of it. The first thing I was wondering if you could try for me was updating the module and reimporting the adventure- we just released an update for the Beginner Box which will refresh the data on placed actors, and may fix your issue immediately! If it doesn't, get back to me and I can delve deeper :)

**Comment by gabihorvath** [comment]
Hello
Thanks for coming back to this. I updated to v4.1.0, but the error sadly still persists.
